name: Veri Hatası Bildirimi
description: Mevcut verilerde hata veya eksiklik bildirmek için bu şablonu kullanın
title: "[HATA] "
labels: ["veri-hatası", "düzeltme"]
body:
  - type: markdown
    attributes:
      value: |
        🐛 **Veri Hatası Bildirimi**
        
        Veritabanımızdaki hatalı veya eksik bilgileri bildirmek için bu formu kullanın.

  - type: input
    id: kurum_adi
    attributes:
      label: Kurum Adı
      description: Hatanın bulunduğu kurumun adı
      placeholder: "Örn: İstanbul Üniversitesi-Cerrahpaşa Tıp Fakültesi Hastanesi"
    validations:
      required: true

  - type: dropdown
    id: hata_tipi
    attributes:
      label: Hata Tipi
      description: Hangi tür bir hata/eksiklik var?
      options:
        - Yanlış kurum adı
        - Yanlış kurum tipi
        - Yanlış adres
        - Yanlış telefon numarası
        - Yanlış web sitesi
        - Yanlış koordinatlar
        - Eksik bilgi
        - Kurum artık mevcut değil
        - Diğer
    validations:
      required: true

  - type: textarea
    id: mevcut_bilgi
    attributes:
      label: Mevcut (Hatalı) Bilgi
      description: Şu anda veritabanında bulunan hatalı bilgi
      placeholder: "Mevcut hatalı bilgiyi buraya yazın"
    validations:
      required: true

  - type: textarea
    id: dogru_bilgi
    attributes:
      label: Doğru Bilgi
      description: Doğru olan bilgiyi yazın
      placeholder: "Doğru bilgiyi buraya yazın"
    validations:
      required: true

  - type: input
    id: kaynak
    attributes:
      label: Kaynak
      description: Bu düzeltmeyi hangi kaynağa dayanarak yapıyorsunuz?
      placeholder: "Örn: Kurum resmi web sitesi, Sağlık Bakanlığı"
    validations:
      required: true

  - type: textarea
    id: ek_aciklama
    attributes:
      label: Ek Açıklama
      description: Varsa ek açıklamalar
