name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Verify static files
      run: |
        echo "Checking static files..."
        ls -la
        echo "Checking index.html exists..."
        [ -f index.html ] && echo "✓ index.html found" || echo "✗ index.html missing"
        echo "Checking JS files..."
        [ -d js ] && echo "✓ js directory found" || echo "✗ js directory missing"
        echo "Checking CSS files..."
        [ -d styles ] && echo "✓ styles directory found" || echo "✗ styles directory missing"
        echo "Checking data files..."
        [ -d data ] && echo "✓ data directory found" || echo "✗ data directory missing"
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        exclude_assets: '.github,scripts,logs,_build,__pycache__,.git*,*.py,*.md,requirements.txt,build.py,*.log'
