name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Process data
        run: |
          python scripts/process_data.py

      - name: Validate data
        run: |
          python scripts/validate_data.py

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Build site
        run: |
          # Copy all necessary files to build directory
          mkdir -p _site
          cp -r . _site/
          # Remove unnecessary files
          rm -rf _site/.git _site/.github _site/scripts _site/requirements.txt
          rm -rf _site/**/*.py _site/**/*.log _site/**/*.md
          rm -rf _site/data/raw
          # Create build info
          echo '{"build_time": "'$(date -u +%Y-%m-%dT%H:%M:%SZ)'", "version": "2.0.3", "commit": "'${GITHUB_SHA}'"}' > _site/build-info.json

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
